export interface Industry {
  slug: string
  name: string
  badgeLabel: string
  code: string
  headline: string
  subtitle: string
}

export const LANDING_SUBTITLE =
  'All the risk is on us. Your platform gets built with no cost, and you only pay a flat monthly fee if you use it. It\u2019ll be ready in days, not months.'

export const LANDING_SUBLINE = '+100 Delivered in 2025'

export const industries: Industry[] = [
  {
    slug: 'construction',
    name: 'Construction',
    badgeLabel: 'Construction Companies',
    code: 'CONSTRUCTION-VIP',
    headline: 'Projects, crews, budgets, timelines.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'insurance',
    name: 'Insurance',
    badgeLabel: 'Insurance Agencies',
    code: 'INSURANCE-VIP',
    headline: 'Policies, claims, agents, renewals.. Your custom platform, built for how your agency actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'staffing',
    name: 'Staffing & Recruiting',
    badgeLabel: 'Staffing Agencies',
    code: 'STAFFING-VIP',
    headline: 'Candidates, placements, clients, timesheets.. Your custom platform, built for how your agency actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'law',
    name: 'Law Practice',
    badgeLabel: 'Law Firms',
    code: 'LAW-VIP',
    headline: 'Cases, clients, deadlines, billing.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'accounting',
    name: 'Accounting',
    badgeLabel: 'Accounting Firms',
    code: 'ACCOUNTING-VIP',
    headline: 'Clients, deadlines, documents, billing.. Your custom platform, built for how your practice actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'marketing',
    name: 'Marketing & Advertising',
    badgeLabel: 'Marketing Agencies',
    code: 'MARKETING-VIP',
    headline: 'Campaigns, clients, assets, reporting.. Your custom platform, built for how your agency actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'architecture',
    name: 'Architecture & Planning',
    badgeLabel: 'Architecture Firms',
    code: 'ARCHITECTURE-VIP',
    headline: 'Projects, drawings, clients, timelines.. Your custom platform, built for how your studio actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'health',
    name: 'Health, Wellness & Fitness',
    badgeLabel: 'Wellness Businesses',
    code: 'HEALTH-VIP',
    headline: 'Clients, bookings, programs, payments.. Your custom platform, built for how your business actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'automotive',
    name: 'Automotive',
    badgeLabel: 'Automotive Businesses',
    code: 'AUTOMOTIVE-VIP',
    headline: 'Inventory, customers, service, sales.. Your custom platform, built for how your dealership actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'medical',
    name: 'Medical Practice',
    badgeLabel: 'Medical Practices',
    code: 'MEDICAL-VIP',
    headline: 'Appointments, patients, staff, billing.. Your custom platform, built for how your practice actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'financial-services',
    name: 'Financial Services',
    badgeLabel: 'Financial Services Firms',
    code: 'FINANCE-VIP',
    headline: 'Clients, portfolios, compliance, reporting.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'it',
    name: 'Information Technology',
    badgeLabel: 'IT Companies',
    code: 'IT-VIP',
    headline: 'Projects, tickets, clients, SLAs.. Your custom platform, built for how your team actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'consulting',
    name: 'Management Consulting',
    badgeLabel: 'Consulting Firms',
    code: 'CONSULTING-VIP',
    headline: 'Engagements, clients, deliverables, billing.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'hospitality',
    name: 'Hospitality',
    badgeLabel: 'Hospitality Businesses',
    code: 'HOSPITALITY-VIP',
    headline: 'Reservations, guests, staff, operations.. Your custom platform, built for how your property actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'logistics',
    name: 'Logistics & Supply Chain',
    badgeLabel: 'Logistics Companies',
    code: 'LOGISTICS-VIP',
    headline: 'Routes, drivers, orders, inventory.. Your custom platform, built for how your operation actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'environmental',
    name: 'Environmental Services',
    badgeLabel: 'Environmental Services Companies',
    code: 'ENVIRONMENTAL-VIP',
    headline: 'Projects, compliance, fieldwork, reporting.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'education',
    name: 'Education Management',
    badgeLabel: 'Education Institutions',
    code: 'EDUCATION-VIP',
    headline: 'Students, courses, faculty, enrollment.. Your custom platform, built for how your institution actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'telecom',
    name: 'Telecommunications',
    badgeLabel: 'Telecom Companies',
    code: 'TELECOM-VIP',
    headline: 'Networks, subscribers, service tickets, billing.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'oil-energy',
    name: 'Oil & Energy',
    badgeLabel: 'Energy Companies',
    code: 'ENERGY-VIP',
    headline: 'Wells, pipelines, compliance, production.. Your custom platform, built for how your operation actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'retail',
    name: 'Retail',
    badgeLabel: 'Retail Businesses',
    code: 'RETAIL-VIP',
    headline: 'Inventory, stores, sales, suppliers.. Your custom platform, built for how your business actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'food-beverages',
    name: 'Food & Beverages',
    badgeLabel: 'Food & Beverage Companies',
    code: 'FOOD-VIP',
    headline: 'Orders, suppliers, inventory, distribution.. Your custom platform, built for how your business actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'investment-management',
    name: 'Investment Management',
    badgeLabel: 'Investment Firms',
    code: 'INVESTMENT-VIP',
    headline: 'Portfolios, clients, compliance, reporting.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'commercial-real-estate',
    name: 'Commercial Real Estate',
    badgeLabel: 'CRE Firms',
    code: 'CRE-VIP',
    headline: 'Properties, tenants, leases, deals.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'transportation',
    name: 'Transportation & Trucking',
    badgeLabel: 'Trucking & Transportation Companies',
    code: 'TRANSPORT-VIP',
    headline: 'Fleet, drivers, routes, dispatch.. Your custom platform, built for how your operation actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'venture-capital',
    name: 'Venture Capital & Private Equity',
    badgeLabel: 'VC & PE Firms',
    code: 'VC-VIP',
    headline: 'Deals, portfolios, LPs, due diligence.. Your custom platform, built for how your fund actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'civil-engineering',
    name: 'Civil Engineering',
    badgeLabel: 'Civil Engineering Firms',
    code: 'CIVILENG-VIP',
    headline: 'Projects, permits, drawings, inspections.. Your custom platform, built for how your firm actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'entertainment',
    name: 'Entertainment',
    badgeLabel: 'Entertainment Companies',
    code: 'ENTERTAINMENT-VIP',
    headline: 'Productions, talent, schedules, budgets.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'biotechnology',
    name: 'Biotechnology',
    badgeLabel: 'Biotech Companies',
    code: 'BIOTECH-VIP',
    headline: 'Trials, research, compliance, data.. Your custom platform, built for how your lab actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'consumer-goods',
    name: 'Consumer Goods',
    badgeLabel: 'Consumer Goods Companies',
    code: 'CPG-VIP',
    headline: 'Products, supply chain, distributors, sales.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'apparel-fashion',
    name: 'Apparel & Fashion',
    badgeLabel: 'Fashion Brands',
    code: 'FASHION-VIP',
    headline: 'Collections, suppliers, orders, inventory.. Your custom platform, built for how your brand actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'nonprofit',
    name: 'Non-Profit Organization Management',
    badgeLabel: 'Non-Profit Organizations',
    code: 'NONPROFIT-VIP',
    headline: 'Donors, programs, grants, volunteers.. Your custom platform, built for how your organization actually runs.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'medical-devices',
    name: 'Medical Devices',
    badgeLabel: 'Medical Device Companies',
    code: 'MEDDEVICE-VIP',
    headline: 'Products, compliance, trials, distribution.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'pharmaceuticals',
    name: 'Pharmaceuticals',
    badgeLabel: 'Pharmaceutical Companies',
    code: 'PHARMA-VIP',
    headline: 'Trials, compliance, pipeline, distribution.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'internet',
    name: 'Internet',
    badgeLabel: 'Internet Companies',
    code: 'INTERNET-VIP',
    headline: 'Users, analytics, integrations, growth.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'computer-software',
    name: 'Computer Software',
    badgeLabel: 'Software Companies',
    code: 'SOFTWARE-VIP',
    headline: 'Releases, customers, support, roadmap.. Your custom platform, built for how your company actually works.',
    subtitle: LANDING_SUBTITLE,
  },
  {
    slug: 'investment-banking',
    name: 'Investment Banking',
    badgeLabel: 'Investment Banks',
    code: 'IB-VIP',
    headline: 'Deals, clients, models, compliance.. Your custom platform, built for how your bank actually works.',
    subtitle: LANDING_SUBTITLE,
  },
]

export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug)
}

export function getAllIndustrySlugs(): string[] {
  return industries.map((i) => i.slug)
}
